os: osx
osx_image: xcode10

before_script:
  - brew install bazel
  - git clone https://github.com/tensorflow/tensorflow

addons:
  homebrew:
    taps:
      - bazelbuild/tap
      - homebrew/cask-versions
    casks: 
      - java8
    update: true
