os: osx
osx_image: xcode10

before_script:
  - brew install bazel
  - git clone https://github.com/tensorflow/tensorflow

script:
  - cd tensorflow
 # - wget https://gist.githubusercontent.com/itsbalamurali/6ab3860435b440d17cdc2fad8dc158cf/raw/f61e74bb208ff4a7e99f950dd5fc109867f6f32a/.tf_configure.bazelrc -O .tf_configure.bazelrc
 # - ./configure
  - bazel build --config=monolithic --python_path=/usr/local/opt/python@2/bin/python2.7  //tensorflow:libtensorflow_cc.so

addons:
  homebrew:
    taps:
      - bazelbuild/tap
      - homebrew/cask-versions
    casks: 
      - java8
    update: true
