os: osx
osx_image: xcode10

before_script:
  - brew install bazel
  - git clone https://github.com/tensorflow/tensorflow

env:
  global:
    - PYTHON_BIN_PATH="/usr/local/opt/python@2/bin/python2.7"
    - TF_NEED_HDFS=0
    - TF_NEED_CUDA=0
    - TF_NEED_ROCM=0
    - TF_NEED_OPENCL_SYCL=0
    - TF_NEED_MKL=0
    - COMPUTECPP_PATH="/usr/local"

script:
  - cd tensorflow
  - yes "" | ./configure
  - bazel build --config=monolithic //tensorflow:libtensorflow_cc.so

addons:
  homebrew:
    taps:
      - bazelbuild/tap
      - homebrew/cask-versions
    casks: 
      - java8
