os: osx
osx_image: xcode10

before_script:
  - brew install bazel
  - git clone https://github.com/tensorflow/tensorflow

script:
  - cd tensorflow
  - ./configure
  - bazel build //tensorflow:libtensorflow_cc.so

addons:
  homebrew:
    taps:
      - bazelbuild/tap
      - homebrew/cask-versions
    casks: 
      - java8
    update: true
