trigger:
- master
pool:
  vmImage: 'macOS-10.13'
variables:
  PATH: "$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
  CC_OPT_FLAGS: '-mavx'
  TF_NEED_HDFS: 0
  TF_NEED_CUDA: 0
  TF_NEED_ROCM: 0
  TF_NEED_OPENCL_SYCL: 0
  TF_NEED_MKL: 0
  COMPUTECPP_PATH: "/usr/local"

steps:
- script: brew install bazel
  displayName: Install Bazel Build
- script: |
    git clone https://github.com/tensorflow/tensorflow --depth=20 
  displayName: Clone TensorFlow
  
- script: |
    cd tensorflow
    python ./configure.py <<-EOF
    yes ""
    EOF
  displayName: Configure TensorFlow Build
  
- script: |
    cd tensorflow
    bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma  --copt=-msse4.2 --config=monolithic //tensorflow:libtensorflow_cc.so
  displayName: Bazel Build
  
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
   
- script: |
    cd tensorflow
    tensorflow/contrib/makefile/download_dependencies.sh
  displayName: Download TensorFlow Dependencies

- script: |
    ls -la
    mkdir -p tensorflow/build_artifacts/lib
    mkdir -p tensorflow/build_artifacts/include/tensorflow
    mkdir -p tensorflow/build_artifacts/include/tensorflow/third_party
    ls -la tensorflow/
    cp -RL ./tensorflow/core $(System.DefaultWorkingDirectory)/tensorflow/build_artifacts/include/tensorflow
    cp -RL ./tensorflow/cc $(System.DefaultWorkingDirectory)/tensorflow/build_artifacts/include/tensorflow
    cp -RL ./tensorflow/third_party/eigen3 $(System.DefaultWorkingDirectory)/third_party
    #rm -rf $DST/third_party/eigen3/unsupported
    cp -RLf ./bazel-tensorflow/external/eigen_archive/unsupported $(System.DefaultWorkingDirectory)/tensorflow/build_artifacts/include/tensorflow
    cp -RL ./bazel-genfiles/tensorflow/cc $(System.DefaultWorkingDirectory)/tensorflow/build_artifacts/include/tensorflow
    cp -RL ./bazel-genfiles/tensorflow/core $(System.DefaultWorkingDirectory)/tensorflow/build_artifacts/include/tensorflow
    cp -RL ./bazel-tensorflow/external/eigen_archive/Eigen $(System.DefaultWorkingDirectory)/tensorflow/build_artifacts/include/Eigen    
    cp bazel-bin/tensorflow/libtensorflow_cc.so $(System.DefaultWorkingDirectory)/tensorflow/build_artifacts/lib/libtensorflow_cc.so
  displayName: Package TensorFlow Build

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'libtensorflow-cc'
    targetPath: '$(System.DefaultWorkingDirectory)/tensorflow/build_artifacts'
