version: 2
jobs:
  build:
    macos:
      xcode: "8.3.3"
    steps:
      - checkout
      - run:
          name: Install Bazel
          command: brew install bazel
      - run:
          name: Clone Tensorflow
          command: git clone https://github.com/tensorflow/tensorflow && cd tensorflow
      - run:
          name: Bazel Build
          command: bazel build -c opt --copt=-mavx --copt=-mavx2 --copt=-mfma  --copt=-msse4.2 --config=monolithic //tensorflow:libtensorflow_cc.so
          environment:
            PATH="$PATH:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
            PYTHON_BIN_PATH="/usr/local/opt/python@2/bin/python2.7"
            CC_OPT_FLAGS='-mavx'
            TF_NEED_HDFS=0
            TF_NEED_CUDA=0
            TF_NEED_ROCM=0
            TF_NEED_OPENCL_SYCL=0
            TF_NEED_MKL=0
            COMPUTECPP_PATH="/usr/local"

      # Collect XML test results data to show in the UI,
      # and save the same XML files under test-results folder
      # in the Artifacts tab
      #- store_test_results:
      #    path: test_output/report.xml
      #- store_artifacts:
      #    path: /tmp/test-results
      #    destination: scan-test-results
      #- store_artifacts:
      #    path: ~/Library/Logs/scan
      #    destination: scan-logs
